version: "3.8"
volumes:
    clickhouse-data:
services:
    clickhouse:
        build:
            context: .
            dockerfile: clickhouse.Dockerfile
        environment:
            CLICKHOUSE_DB: somsiad
            CLICKHOUSE_USER: somsiad
            CLICKHOUSE_PASSWORD: somsiad
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - clickhouse-data:/var/lib/clickhouse/data
    bot:
        build: .
        restart: on-failure
        stop_grace_period: 20s
        depends_on:
            - clickhouse
        links:
            - clickhouse:clickhouse
        environment:
            - DISCORD_TOKEN
            - COMMAND_PREFIX
            - COMMAND_COOLDOWN_PER_USER_IN_SECONDS
            - GOOGLE_KEY
            - GOOGLE_CUSTOM_SEARCH_ENGINE_ID
            - GOODREADS_KEY
            - TMDB_KEY
            - LAST_FM_KEY
            - YANDEX_TRANSLATE_KEY
            - WOLFRAM_ALPHA_APP_ID
            - DISCO_MAX_FILE_SIZE_IN_MIB
            - SENTRY_DSN
            - SENTRY_AUTH_TOKEN
            - SENTRY_ORG
            - DATABASE_URL
            - CLICKHOUSE_URL=http://clickhouse:8123
            - CLICKHOUSE_USER=somsiad
            - CLICKHOUSE_PASSWORD=somsiad
        ports:
            - "80:80"
