version: "3.8"
volumes:
    postgres-data:
#    clickhouse-data:
services:
    postgres:
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        image: postgres:13
        ports:
            - '5439:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
#    clickhouse:
#        image: yandex/clickhouse-server
#        ports:
#            - '8123:8123'
#            - '9000:9000'
#            - '9440:9440'
#            - '9009:9009'
#        volumes:
#            - clickhouse-data:/var/lib/clickhouse/data
    bot:
        build: .
        restart: on-failure
        stop_grace_period: 20s
        depends_on:
            - postgres
        environment:
            - DISCORD_TOKEN
            - COMMAND_PREFIX
            - COMMAND_COOLDOWN_PER_USER_IN_SECONDS
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - GOOGLE_KEY
            - GOOGLE_CUSTOM_SEARCH_ENGINE_ID
            - GOODREADS_KEY
            - TMDB_KEY
            - LAST_FM_KEY
            - YANDEX_TRANSLATE_KEY
            - WOLFRAM_ALPHA_APP_ID
            - DISCO_MAX_FILE_SIZE_IN_MIB
            - SENTRY_DSN
            - SENTRY_AUTH_TOKEN
            - SENTRY_ORG
            - PTVSD
        ports:
            - "5678:5678"
