version: "3.8"
volumes:
  clickhouse-persistence:
services:
  bot:
    build: .
    restart: on-failure
    stop_grace_period: 20s
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - DISCORD_TOKEN
      - COMMAND_PREFIX
      - COMMAND_COOLDOWN_PER_USER_IN_SECONDS
      - GOOGLE_KEY
      - GOOGLE_CUSTOM_SEARCH_ENGINE_ID
      - GOODREADS_KEY
      - TMDB_KEY
      - LAST_FM_KEY
      - WOLFRAM_ALPHA_APP_ID
      - OPENAI_API_KEY
      - DISCO_MAX_FILE_SIZE_IN_MIB
      - SENTRY_DSN
      - SENTRY_AUTH_TOKEN
      - SENTRY_ORG
      - DATABASE_URL
      - CLICKHOUSE_URL
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - CLICKHOUSE_DATABASE
      - REDIS_URL
