version: "3.8"
services:
    bot:
        build: .
        restart: on-failure
        stop_grace_period: 20s
        environment:
            - DISCORD_TOKEN
            - COMMAND_PREFIX
            - COMMAND_COOLDOWN_PER_USER_IN_SECONDS
            - GOOGLE_KEY
            - GOOGLE_CUSTOM_SEARCH_ENGINE_ID
            - GOODREADS_KEY
            - TMDB_KEY
            - LAST_FM_KEY
            - YANDEX_TRANSLATE_KEY
            - WOLFRAM_ALPHA_APP_ID
            - DISCO_MAX_FILE_SIZE_IN_MIB
            - SENTRY_DSN
            - SENTRY_AUTH_TOKEN
            - SENTRY_ORG
            - PTVSD
            - DATABASE_URL
        ports:
            - "80:80"
            - "5678:5678"
