version: "3.8"
services:
    postgres:
        environment:
            POSTGRES_DB: somsiad
            POSTGRES_PASSWORD: somsiad
            POSTGRES_USER: somsiad
        image: postgres:13
        ports:
            - '5439:5432'
    clickhouse:
        build:
            context: .
            dockerfile: clickhouse.Dockerfile
        environment:
            CLICKHOUSE_DB: somsiad
            CLICKHOUSE_USER: somsiad
            CLICKHOUSE_PASSWORD: somsiad
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
    bot:
        build: .
        restart: on-failure
        stop_grace_period: 20s
        depends_on:
            - postgres
            - clickhouse
            - redis
        links:
            - postgres:postgres
            - clickhouse:clickhouse
            - redis:redis
        environment:
            - DISCORD_TOKEN
            - COMMAND_PREFIX
            - COMMAND_COOLDOWN_PER_USER_IN_SECONDS
            - GOOGLE_KEY
            - GOOGLE_CUSTOM_SEARCH_ENGINE_ID
            - GOODREADS_KEY
            - TMDB_KEY
            - LAST_FM_KEY
            - YANDEX_TRANSLATE_KEY
            - WOLFRAM_ALPHA_APP_ID
            - DISCO_MAX_FILE_SIZE_IN_MIB
            - SENTRY_DSN
            - SENTRY_AUTH_TOKEN
            - SENTRY_ORG
            - PTVSD
            - DATABASE_URL=postgres://somsiad:somsiad@postgres/somsiad
            - CLICKHOUSE_URL=http://clickhouse:8123
            - CLICKHOUSE_USER=somsiad
            - CLICKHOUSE_PASSWORD=somsiad
            - REDIS_URL=redis://redis:6379/
        ports:
            - "5678:5678"
    web:
        build: web
        depends_on:
            - redis
        links:
            - redis:redis
        environment:
            - REDIS_URL=redis://redis:6379/
        ports:
            - '5000:5000'
        labels:
            - "traefik.http.routers.web.rule=Host(`localhost`)"
    router:
        image: "traefik:v2.4"
        command:
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.docker=true
            - --api.insecure
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
