apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  clusterIP: None
  ports:
    - name: headless
      port: 55555
      targetPort: 0
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: redis://somsiad-redis-master-0.somsiad-redis-headless:6379/
          image: twixes/somsiad-web:latest
          imagePullPolicy: Always
          name: web
          resources: {}
      restartPolicy: Always
status: {}
