name: Docker
on:
  push:
    branches: ['master']
    paths-ignore:
      - helm/
      - .vscode/
      - terraform-oci/
      - tests/
      - '*.md'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: twixes
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: 'linux/amd64,linux/arm64'
      - name: Build and push bot
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: twixes/somsiad:latest
          platforms: 'linux/amd64,linux/arm64'
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push website
        uses: docker/build-push-action@v3
        with:
          push: true
          context: web
          tags: twixes/somsiad-web:latest
          platforms: 'linux/amd64,linux/arm64'
          cache-from: type=gha
          cache-to: type=gha,mode=max
