name: Scaleway

on:
    push:
        branches:
            - master
            - main

jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Scaleway's Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.pl-waw.scw.cloud/somsiad
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rg.pl-waw.scw.cloud/somsiad/somsiad:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
